import type { Metadata } from 'next'
// import AuthSetup from './components/AuthSetup'
import 'material-symbols/outlined.css'
import { Epilogue } from 'next/font/google'
import AuthSetup from './_components/AuthSetup'
import Navbar from './_components/Navbar'
import './globals.css'

const epilogFont = Epilogue({
    variable: '--font-epilogue',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${epilogFont.variable} antialiased`}>
                <AuthSetup />
                <Navbar />
                <div className="pl-56">{children}</div>
            </body>
        </html>
    )
}
